### ISSUE TITLE
测试跑不通

### ISSUE THREAD

**Issue by vs-learner-llg** [kkkunnnnethan/R-YOLOv4#9]
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python detect.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, image_folder='data/detect', img_size=800, nms_thres=0.2, weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    box = post_process(output, args.conf_thres, args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by kkkunnnnethan** [comment]
可以幫我試試看跑evaluate.py能不能跑嗎 （detect和evaluate要用UCAS-AOD weights, yolov4_train是給train時用的）

**Comment by vs-learner-llg** [comment]
> 可以帮我试试看跑evaluate.py能不能跑吗（

你这个map之前是咋得出来的啊，你之前没有跑过吗，还有AOD_800.pth是干啥的

**Comment by kkkunnnnethan** [comment]
> > 可以帮我试试看跑evaluate.py能不能跑吗（
> 
> 你这个map之前是咋得出来的啊，你之前没有跑过吗，还有AOD_800.pth是干啥的

如果evaluate.py可以的話照理來說detect.py也要可以才對，我晚點會幫你看看。.pth是pytorch使用的weights檔案。

**Comment by vs-learner-llg** [comment]
> evaluate.py
这个脚本没有啊，evaluate.py，只有test.py,train.py/detect.py
python test.py
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.7, img_size=608, iou_thres=0.5, nms_thres=0.2, test_folder='data/test', weights_path='/home/hdsx/llg/R-YOLOv4-master/weights/yolov4_train.pth')
Compute mAP...
['data/test/0/P0226.png']
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    outputs = post_process(outputs, conf_thres=args.conf_thres, nms_thres=args.nms_thres)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/post_process.py", line 34, in post_process
    large_overlap = skewiou(detect[0, :5], detect[:, :5]) > nms_thres
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 67, in skewiou
    g = np.stack(xywha2xyxyxyxy(box1))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 48, in xywha2xyxyxyxy
    P = rotate(x, y, a, P)
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 28, in rotate
    P = np.dot(T(center_x, center_y), np.dot(R(a), np.dot(T(-center_x, -center_y), p)))
  File "/home/hdsx/llg/R-YOLOv4-master/tools/utils.py", line 13, in R
    r = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
  File "/home/hdsx/anaconda3/envs/R-YOLOv4/lib/python3.6/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by vs-learner-llg** [comment]
> > > 可以帮我试试看跑evaluate.py能不能跑吗（
> > 
> > 
> > 你这个map之前是咋得出来的啊，你之前没有跑过吗，还有AOD_800.pth是干啥的
> 
> 如果evaluate.py可以的話照理來說detect.py也要可以才對，我晚點會幫你看看。.pth是pytorch使用的weights檔案。
感谢作者回答，辛苦了谢谢

**Comment by kkkunnnnethan** [comment]
> > > 可以帮我试试看跑evaluate.py能不能跑吗（
> > 
> > 
> > 你这个map之前是咋得出来的啊，你之前没有跑过吗，还有AOD_800.pth是干啥的
> 
> 如果evaluate.py可以的話照理來說detect.py也要可以才對，我晚點會幫你看看。.pth是pytorch使用的weights檔案。
> 感谢作者回答，辛苦了谢谢

阿說錯了 我應該要說test.py
bug修好了，主要是資料在cpu和gpu之間轉換的問題，不好意思之前沒有注意到，謝謝你提出這個問題，如果還有任何問題歡迎再提出。再提醒一下 AOD_800.pth 這個檔案是給detect.py和test.py用的，是我已經train好的模型檔案

**Comment by vs-learner-llg** [comment]
我刚才试了一下test.py和eval.py都可以跑通了，我想问一下有没有脚本把数据集分一下训练集和测试集如何划分，以及map如何计算，可以知道一下不

**Comment by vs-learner-llg** [comment]
还有一个问题就是推理时间好长啊，
![image](https://user-images.githubusercontent.com/50699813/106458126-e1d5f900-64ca-11eb-8734-8ec993db83c6.png)

**Comment by kkkunnnnethan** [comment]
> 还有一个问题就是推理时间好长啊，
> ![image](https://user-images.githubusercontent.com/50699813/106458126-e1d5f900-64ca-11eb-8734-8ec993db83c6.png)

我沒有特別寫一個分訓練跟測試集的function，我是直接手動分開的。mAP的計算建議直接上網查了解會比較好哦。
如果模型偵測到太多有可能是物體的物體（也就是confidence > confs_thresh），就有可能會造成後處理的時間太久。這部分我有想辦法改善了但是我目前最快只能到這樣... 你可以想辦法improve！

**Comment by vs-learner-llg** [comment]
> 我沒有特別寫一個分訓練跟測試集的function，我是直接手動分開的。mAP的計算建議直接上網查了解會比較好哦。
> 如果模型偵測到太多有可能是物體的物體（也就是很多grid的confidence > confs_thresh），就有可能會造成後處理的時間太久。這部分我有想辦法改善了但是我目前最快只能到這樣... 你可以想辦法improve！

好的，谢谢，辛苦了
